# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: firstuser
  CLOUD_SQL_PASSWORD: 12345678
  CLOUD_SQL_DATABASE_NAME: firstdatabase
  CLOUD_SQL_CONNECTION_NAME: third-project-339116:us-central1:first-instance
# [END gae_python37_cloudsql_config]
